# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_beneficiario', models.CharField(max_length=8, null=True, unique=True, verbose_name='Cedula (*)')),
                ('nombres', models.CharField(max_length=40, null=True, verbose_name='Nombres (*)')),
                ('apellidos', models.CharField(max_length=40, null=True, verbose_name='Apellidos (*)')),
                ('profecion_beneficiario', models.CharField(max_length=200, null=True, verbose_name='Profesion (*)')),
                ('sitio_traba', models.CharField(max_length=200, null=True, verbose_name='Sitio de Trabajo (*)')),
                ('ingre_mensu_beneficiario', models.CharField(max_length=100, null=True, verbose_name='Ingreso Mensual (*)')),
                ('correo', models.EmailField(max_length=100, null=True, verbose_name='Correo Electronico (*)')),
                ('telefono', models.CharField(max_length=7, verbose_name='Telefono (*)')),
                ('movil', models.CharField(max_length=7, null=True, verbose_name='Movil (*)')),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliado.Afiliado', verbose_name='Afiliado (*)')),
            ],
        ),
    ]
