# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reposo',
            fields=[
                ('reposo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Reposo (*)')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo (*)')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario', verbose_name='Beneficiario')),
            ],
        ),
    ]
