# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre (*)')),
                ('tipo', models.CharField(max_length=40, verbose_name='Tipo (*)')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso (*)')),
            ],
        ),
    ]
