# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('afiliado', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_afiliado', models.CharField(max_length=8, null=True, unique=True, verbose_name='Cedula (*)')),
                ('nombres', models.CharField(max_length=40, null=True, verbose_name='Nombres (*)')),
                ('apellidos', models.CharField(max_length=40, null=True, verbose_name='Apellidos (*)')),
                ('num_familia', models.CharField(max_length=200, null=True, verbose_name='Numero de Familia (*)')),
                ('direccion', models.TextField(max_length=500, null=True, verbose_name='Direccion (*)')),
                ('profecion_afiliado', models.CharField(max_length=200, null=True, verbose_name='Profesion (*)')),
                ('sitio_traba', models.CharField(max_length=200, null=True, verbose_name='Sitio de Trabajo (*)')),
                ('ingre_mensu_afiliado', models.CharField(max_length=100, null=True, verbose_name='Ingreso Mensual (*)')),
                ('correo', models.EmailField(max_length=100, null=True, verbose_name='Correo Electronico (*)')),
                ('telefono', models.CharField(max_length=7, verbose_name='Telefono (*)')),
                ('movil', models.CharField(max_length=7, null=True, verbose_name='Movil (*)')),
                ('sector', models.CharField(blank=True, max_length=50, verbose_name='Sector (*)')),
                ('comunidad', models.CharField(blank=True, max_length=50, verbose_name='Comunidad (*)')),
                ('avenidad', models.CharField(blank=True, max_length=50, verbose_name='Avenidad (*)')),
                ('calle', models.CharField(blank=True, max_length=50, verbose_name='Calle (*)')),
                ('casa', models.CharField(blank=True, max_length=50, verbose_name='casa (*)')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.Institucion', verbose_name='Institucion (*)')),
            ],
        ),
    ]
