# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-17 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiliado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='apellidos',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='avenidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='calle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='casa',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='cedula_afiliado',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='comunidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='correo',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='direccion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='ingre_mensu_afiliado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.Institucion'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='movil',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='nombres',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='num_familia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='profecion_afiliado',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='sector',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='sitio_traba',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='telefono',
            field=models.CharField(max_length=7),
        ),
    ]
